### ISSUE TITLE
undefined function Random.string/0

### ISSUE THREAD

**Issue by ryanmcgarvey** [gutschilla/elixir-pdf-generator#1]
Attempted to run the tutorial in a simple app - got this message.

Looks like everything is being pulled in, but the Alias from Misc.Random to Random isn't being called.

**Comment by gutschilla** [comment]
Hi Ryan, thanks for pointing me to this! Apparently, mix/hex doesn't pull dependencies that aren't on hex.pm. Your error sais: 
```
(module PlugSessionMEMCACHED is not available)
```
So one has to include this in your deps section:
```
 {:mcd, github: "EchoTeam/mcd"}
```
I updated the README section as well. Again, thanks a lot for your contribution!

**Comment by gutschilla** [comment]
Hi @ryanmcgarvey , I fixed this naming issue (I moved a module from `Random` to `Misc.Random`) by both publishing Misc.Random to hex for automatic pulls by `mix deps.get` and aliased Misc.Random - thanks a million for reporting and supplying the aliasing hint.

Now, it should compile and work.
