### ISSUE TITLE
:command_prefix config

### ISSUE THREAD

**Issue by hisapy** [gutschilla/elixir-pdf-generator#10]
In the README it says you can pass `:command_prefix` to `:pdf_generator` config.  However from code in tag v0.3.3 you can see that `:command_prefix` option is not actually implemented yet. I didn't know that option wasn't actually advertised in [hex docs](https://hexdocs.pm/pdf_generator/PdfGenerator.html) ... I was reading the README in master and in v0.3.0 branches. 

Are you planning on pushing that option to Hex anytime soon ?

**Comment by gutschilla** [comment]
@hisapy @cdale77 Sorry for being unresponsive these days. On your qurstion: yes: The feature resides in the [xvfb_support](https://github.com/gutschilla/elixir-pdf-generator/tree/xvfb_support) branch and the documentation for it accidentally made into the README before releasing it. Shame on me :-(

To really answer your question: Yes, I do. I'm on it.

**Comment by hisapy** [comment]
Thx @gutschilla

**Comment by gutschilla** [comment]
It's in 0.3.4, PLS see: https://hex.pm/packages/pdf_generator and tell me what you think

**Comment by cdale77** [comment]
Cool! I haven't had a chance to try it out -- I read your code and got the idea of using Porcelain directly, which was a cool experience. I'll probably go back and use your implementation, and will let you know. thanks!

**Comment by gutschilla** [comment]
@cdale77 Yeah, in the end this is just a wrapper around porcelain and wkhtmltopdf (and pdftk and xvfb) providing some hopefully sane defaults. The main functionality lies in a few lines interfacing porcelain. So if you're good with rolling your own, I am very happy to have shown the road down there.

Thanks for the info!
