### ISSUE TITLE
Question: Why Agent?

### ISSUE THREAD

**Issue by hisapy** [gutschilla/elixir-pdf-generator#11]
I'm relatively newbie in Elixir. I'm curious about why you setup an **Agent** for the elixir-pdf-generator. 

Is it really necessary to depend on porcelain and goon(_optional_) to just call the underlying `wkhtmltopdf`?

**Comment by gutschilla** [comment]
Thanks for the questions!

- It works perfectly without goon. I plan to eventually dismiss the usage of temp file for proper IPC. Therefore goon would be cool
- Porcelain is a really cool wrapper around erlang ports which does proper shell-out handling. I want to track exec return values and crashes.
- The Agent is there to hold state. This way, I need to call `System.find_executable` only once at startup when no paths are configured

**Comment by gutschilla** [comment]
More on the Agent: It could be done via `Application.put_env` as well but this module is very old (in Elixir terms) and honestly, I didn't know about this back then :-)

**Comment by hisapy** [comment]
👍  thanks again. 

Just a minor request: I'd like tmp file vs IPC to be configurable.
