### ISSUE TITLE
initial demo fails: ** (FunctionClauseError) no function clause matching in Porcelain.exec/3

### ISSUE THREAD

**Issue by dgoldie** [gutschilla/elixir-pdf-generator#14]
porcelain 2.0.2 is in the _build and it certainly has exec/3.
the full stacktrace is below.

Any thoughts on what I did wrong would be appreciated.
thanks, -doug.

```
versions: Phoenix v1.2.1, Elixir 1.3.2, Erlang 19

This is a new phoenix app with these configs:
  def application do
    [mod: {FlyerMaker, []},
     applications: [:phoenix, :phoenix_pubsub, :phoenix_html, :cowboy, :logger, :gettext,
                    :phoenix_ecto, :postgrex, :pdf_generator]]
  end

  # Type `mix help deps` for examples and options.
  defp deps do
    [{:phoenix, "~> 1.2.1"},
     {:phoenix_pubsub, "~> 1.0"},
     {:phoenix_ecto, "~> 3.0"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.6"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:gettext, "~> 0.11"},
     {:cowboy, "~> 1.0"},
     {:pdf_generator, ">=0.3.0"}]
  end

➜  flyer_maker git:(master) ✗ iex -S mix
Erlang/OTP 19 [erts-8.0.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Compiling 12 files (.ex)
Generated flyer_maker app
Interactive Elixir (1.3.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> html = "<html><body><p>Hi there!</p></body></html>"
"<html><body><p>Hi there!</p></body></html>"
iex(2)> { :ok, filename }    = PdfGenerator.generate html, page_size: "A5", open_password: "s3cr3t" 
** (FunctionClauseError) no function clause matching in Porcelain.exec/3
        (porcelain) lib/porcelain.ex:127: Porcelain.exec(nil, ["/var/folders/fh/p_0tnm5j46lc5n00hkhzyzyw0000gn/T/zaa6W1Lz.pdf", "output", "/var/folders/fh/p_0tnm5j46lc5n00hkhzyzyw0000gn/T/iY7m1x9n.pdf", "owner_pw", "YEYmQWQv0jGdytPT", "user_pw", "s3cr3t", "encrypt_128bit", "allow", "Printing", "CopyContents"], [])
    (pdf_generator) lib/pdf_generator.ex:160: PdfGenerator.encrypt_pdf/3
iex(2)> 
```

**Comment by dgoldie** [comment]
Ok, this fails because in this function is only looks for the pdftk_path, 
which is nil in my case because I didn't install it. I thought it was optional :-)
The docs imply that wkhtmltopdf  is the default.

Which Porcelain exec function is best practice with wkhtmltopdf?
btw: I can't find pdftk to install on brew.

thanks, 
-doug.

**Comment by gutschilla** [comment]
Hi @dgoldie - Thanks a lot for your report. Sure, `pdftk` should be optional. I am not on a Mac so I have no idea why it isn't available via your favorite package manager. But there are sources and binaries available here: https://www.pdflabs.com/tools/pdftk-server/ 

I will make sure that pdftk is realy optional.

**Comment by gutschilla** [comment]
On Porcelain: both variant with or without goon do work. Since the author of Porcelain suggests using goon, I simply installed it.

**Comment by lypborges** [comment]
@dgoldie
I had the same error on MAC when I try the demo. 
Then I realize we should run the command like this `{ :ok, filename }    = PdfGenerator.generate html, page_size: "A5"`without the open_password option.

@gutschilla, tks for this work. Maybe it's better to remove this option from the sample command on README.md

```
$ iex -S mix

html = "<html><body><p>Hi there!</p></body></html>"
# be aware, this may take a while...
{ :ok, filename }    = PdfGenerator.generate html, page_size: "A5" 
{ :ok, pdf_content } = File.read filename 

# or, if you prefail methods that rais on error:
filename             = PdfGenerator.generate! html
```

**Comment by gutschilla** [comment]
@lypborges Thanks a lot pointing me there. It's addressed in current master. You're absolutely right.
