### ISSUE TITLE
How to include stylesheets in generated pdfs.

### ISSUE THREAD

**Issue by CrowdHailer** [gutschilla/elixir-pdf-generator#16]
Hi I am switching a project from Ruby to elixir. previously I was using [PDFKit](https://github.com/pdfkit/pdfkit). It had a few helpers for including stylesheets that I don't know how to recreate with elixir-pdf-generator.

My html page is shown as both HTML and PDF. I have a stylesheet that is served from the same server as the html page.
In my html is this line
```html
<link rel="stylesheet" href="/stylesheets/licence.css" media="screen" title="no title" charset="utf-8">
```
How do I get this file included in the generated pdf. 

I think the answer is to convert the relative filepath into an absolute one. 
I'm not sure if I should convert it to the hosted location of the stylesheet or the location in the server file structure.

```elixir
  uri = %URI{host: request.host, scheme: "http", port: request.port, path: "/stylesheets/licence.css"}
  html = String.replace(html, "href=\"/stylesheets/licence.css\"", "href=\"uri\"")
```

OR

```elixir
  uri = %URI{host: request.host, scheme: "http", port: request.port, path: "/stylesheets/licence.css"}
  html = String.replace(html, "href=\"/stylesheets/licence.css\"", "href=\"#{Application.app_dir(:my_app)}/stylesheets/licence.css\"")

Any pointers would be greatly apprechiated
```

**Comment by radik909** [comment]
I think you could use [EEx.eval_file](https://hexdocs.pm/eex/EEx.html#eval_file/3) for achieving this.

**Comment by gutschilla** [comment]
@CrowdHailer Hi, rorry for my late reply. I usually serve CSS from a webserver (locally) and let the HTML generating the PDF point there. Or - the quick and dirty variant - I just include the CSS in the HTML's header.
