### ISSUE TITLE
[Question] How to use it on phoenix

### ISSUE THREAD

**Issue by lypborges** [gutschilla/elixir-pdf-generator#18]
Hi,

I'm look for documentation or sample on how to use it with phoenix. Sorry if it's a dummy question, but I'm new to elixir and phoenix.  But I need to do some thing like this ruby code.

```ruby
  def print
    respond_to do |format|
        format.html do
          render file: "/pipedrive/#{@template}.html.erb"
        end
        format.pdf do
          render  :pdf => "#{@proposal["title"]} - #{@proposal["organization"]["name"]}",
                  :template => "/pipedrive/#{@template}.html.erb"
        end
      end
  end
```

So I need to give the name and render the choose template with all variables in PDF.

**Comment by lypborges** [comment]
I found how. 

```elixir
html = "<html><body><p>Hi there!</p></body></html>"
    { :ok, filename }    = PdfGenerator.generate html, page_size: "A5"

    conn
      |> put_resp_content_type("application/octet-stream", nil)
      |> put_resp_header("content-disposition", ~s[attachment; filename="hello.pdf"])
      |> send_file(200, filename)
```

**Comment by gutschilla** [comment]
@lypborges Very good you found out that. Still, this module is intended to handle HTML strings to PDF binary conversion only.

I do use in a Phoenix project exposing an HTTP API to it and apparently use a very similar code here: https://github.com/gutschilla/elixir-pdf-server/blob/master/web/controllers/generator_controller.ex

**Comment by lypborges** [comment]
Tks a lot. ;)
