### ISSUE TITLE
[Question] - Use image tag

### ISSUE THREAD

**Issue by lypborges** [gutschilla/elixir-pdf-generator#19]
The only way I could make a image appear on pdf is passing the absolute path, I thinks this is the way Wkthmltopdf works according this [issue](https://github.com/mileszs/wicked_pdf/issues/36). 

So I need to do that:

```html
<header>
  <img style="display: block; margin: 0 auto;" src="file:///Users/root/GitHub/projects/my-app/web/static/images/logo.png" alt="" />
</header>
```

Is there a way of use relative path ?
I'm using the same style I had on my other ruby project and is not being applied. Any idea why?

**Comment by lypborges** [comment]
I made a function like this on my view:

```exlixir
  def image_tag_pdf(file_name) do
    static_path = "/web/static/images/" <> file_name
    abs_path = Path.expand(".")
    image_path = abs_path <> static_path
    img_tag(image_path)
  end
```

And in my html template:

```html
  <%= image_tag_pdf("logo.png")%>
```

I can make a PR for documentation or should we try to include this helper function on the project?

P.s: Still working on the css for the image.

**Comment by gutschilla** [comment]
You certainly **can** use relative paths.

Keep in mind that the images, css files or whatnot have to be relative to the workdir in which the underlying whtmltopdf is being called. Usually, this would be the base directory of your elixir project (where your mixfile resides in).

You may as well use absolute paths – but keep in mind this will make deployments to other environments with different paths harder or at least something you'll need to configure.

**Hint:** As long as you are generating PDFs for a webservice (for example, within a Phoenix project) it's super easy to just put the image in a directory that is served by Phoenix anyways. You seem to be doing this in your example as well (`/web/static/images/<image>`). The solution is to source the image by http. Simply use the image's URL. Wkhtmltopdf will resolve this on it's own, pulling the image from your web service.

To get rid of this http round trip one could imagine to set the base path for wkhtmltopdf and then cwd into there before calling out. Nice idea!

**Comment by gutschilla** [comment]
@lypborges I made a feature request from that. Since relative paths would probably more helping. PLS track https://github.com/gutschilla/elixir-pdf-generator/issues/20

**Comment by Dolo86rv** [comment]
Hi!. In my project I have this image: bitwalker/alpine-elixir-phoenix:1.14 and when I execute apk add --update ncurses-libs qpdf wkhtmltopdf it shows the following error.
