### ISSUE TITLE
undefined function Random.string/0

### ISSUE THREAD

**Issue by schurig** [gutschilla/elixir-pdf-generator#2]
Hey, I'm getting this error when trying to implement `pdf_generator` into my phoenixframework app:

`undefined function Random.string/0 (module Random is not available)`

I tried putting

```elixir
{:pdf_generator, "0.2.0"} AND {:misc_random, ">=0.2.5" }
```

into my `mix.exs` but It didn't solve the problem. Also I load both modules into my application in the `mix.exs` file.

**Comment by gutschilla** [comment]
Hi Martin, 
Thanks for reporting the issue. I have to update the README - you have to include misc_random in your included_apps. Please look at

https://github.com/gutschilla/phoenix-skeleton/blob/master/mix.exs

on ho to hadd this to your mixfile. Stay tune for an updat I the docs.

**Comment by gutschilla** [comment]
Just to be clear on this: you did actually include it in your application's section? Will you please point me to the repo in question so I can dig into this? Thanks again for reporting, Martin

**Comment by schurig** [comment]
I included it in the deps and application section:

```elixir
def application do
  [mod: {MyApp, []},
   applications: [:phoenix, :phoenix_html, :phoenix_ecto, :cowboy, :logger, :gettext] ++
                 [:postgrex, :oauth2, ..., :pdf_generator, :misc_random, :quantum]]
end
```

```elixir
defp deps do
  [{:phoenix, "~> 1.1.2"},
   {:phoenix_ecto, "~> 2.0"},
   {:postgrex, ">= 0.0.0", override: true},
   {:phoenix_html, "2.4.0"},
   {:phoenix_live_reload, "~> 1.0", only: :dev},
   ....
   {:pdf_generator, "0.2.0"},
   {:misc_random, ">=0.2.5" },
   {:quantum, ">= 1.6.1"}]
end
```

I was trying to figure out how to use it so I just put the following code into some random controller and called it:

```elixir
html = "<html><body><p>Hi there!</p></body></html>"
# be aware, this may take a while...
{ :ok, file_name } = PdfGenerator.generate html, page_size: "A4"
{ :ok, _pdf_content } = File.read file_name
IO.puts "##########################"
IO.puts file_name
```

**Comment by gutschilla** [comment]
This should be resolved, now. Please update your mixfile to the following:
```
def application do
    [applications: [
        :logger, 
        :pdf_generator # <-- add this
    ]]
end

...

defp deps do
    [
        # ... whatever else
        { :pdf_generator, ">=0.3.0" }, # <-- and this
    ]
end
```

This should automatically fetch and start both :pdf_generator and :misc_random. At least in my test, it does. Please tell me if you run into any issues.

**Comment by schurig** [comment]
It's working!! Thank you!!!! :)

**Comment by gutschilla** [comment]
Great! Thanks again for reporting on that issue.
