### ISSUE TITLE
heroku-pdftk-buildpack not building on heroku

### ISSUE THREAD

**Issue by CrowdHailer** [gutschilla/elixir-pdf-generator#25]
Hi, I am trying to work through the instructions in the README for setting up a PDF generator on heroku.

My list of buildpacks looks like this

```
1. https://github.com/fxtentacle/heroku-pdftk-buildpack.git
2. https://github.com/dscout/wkhtmltopdf-buildpack.git
3. https://github.com/HashNuke/heroku-buildpack-elixir
4. heroku/ruby
```

However it looks like it is failing on the very first one. 

```
remote: Building source:
remote: 
remote: -----> heroku-pdftk-buildpack app detected
remote: cp: cannot stat 'binaries-heroku-16/*': No such file or directory
remote:  !     Push rejected, failed to compile heroku-pdftk-buildpack app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to my-app.
remote: 
```

Has anyone suffered a similar problem/ have any pointers?

**Comment by gutschilla** [comment]
Hey @CrowdHailer Thanks a lot for addressing this. The instructions were added by @jbhatab in https://github.com/gutschilla/elixir-pdf-generator/pull/21 . This worked a month ago but I am unable myself to debug this right now. 

@jbhatab Any ideas?

**Comment by CrowdHailer** [comment]
Thanks for the prompt @gutschilla I have not got it to work and am having to try the heroku addons like docraptor instead

**Comment by jbhatab** [comment]
@CrowdHailer what heroku stack are you on? Cedar or heroku-16?

**Comment by CrowdHailer** [comment]
I'm using heroku-16

**Comment by gutschilla** [comment]
@jbhatab @CrowdHailer Thanks for taking on this!

**Comment by gutschilla** [comment]
Addressed and documented in https://github.com/gutschilla/elixir-pdf-generator/pull/21

**Comment by manojmilani** [comment]
@gutschilla  I am pushing code to github which is connected to heroku instance. But I am failing to deploy and getting the below error. Can you please help? I have added buildpacks as well:

``
Preparing runtime environment...
-----> Checking for additional extensions to install...
-----> heroku-pdftk-buildpack app detected
cp: cannot stat 'binaries-heroku-18/*': No such file or directory
 !     Push rejected, failed to compile heroku-pdftk-buildpack app.
 !     Push failed
``
