### ISSUE TITLE
Pass arguments to command_prefix

### ISSUE THREAD

**Issue by tonyvanriet** [gutschilla/elixir-pdf-generator#29]
When we use the `:command_prefix` option to run `wkhtmltopdf` within `xvfb`, we found that when we run `generate!` multiple times in rapid succession, it will eventually fail showing a `Xvfb failed to start` error.

We were able to reproduce the failure directly at the command line and got this more verbose output from xvfb.

```
Fatal server error:
(EE) Server is already active for display 99
	If this server is no longer running, remove /tmp/.X99-lock
	and start again.
```

The `-a ` option for `xvfb-run` allows it to look for a free server number rather than assuming 99, and using this resolved our intermittent failure.

But, because of the way the command is formed for `Porcelain.exec`, it's not possible for us to just include the `-a` flag in the `:command_prefix` config.

We're interested in submitting a PR for this, but I wanted to make sure that would be welcome and see if you had any thoughts on how it should be handled. 

Some ideas so far:
1) split the `:command_prefix` config value on the first whitespace and assume anything after the split are arguments that are similarly prepended to the arguments returned by `make_command_tuple`
2) add a `:command_prefix_arguments` config option and prepend those to the second element returned by `make_command_tuple`

**Comment by tonyvanriet** [comment]
I realize now that we see the same failure when we run the tests for this repo. This makes me think that you have found some other way around this problem, or there is some environmental difference that causes us to be more susceptible.

**Comment by gutschilla** [comment]
@tonyvanriet Thanks a lot for your fine comment and request! I am very sorry for the utterly late reply :grimacing:  Anyways, I am ver glad to accept PRs to address issues.

**Comment by gutschilla** [comment]
@tonyvanriet Done. I'll draft a new release anytime soon. Promise! :-)

**Comment by gutschilla** [comment]
@tonyvanriet A small-ish thing. Could you please add this use case to the README? 

Thanks a million for your support!

**Comment by tonyvanriet** [comment]
No problem @gutschilla. I posted #36 to document the use case.
Thanks to @larryweya for the implementation.

**Comment by gutschilla** [comment]
Addressed and solved in https://github.com/gutschilla/elixir-pdf-generator/pull/36
