### ISSUE TITLE
Generate pdf without saving a file

### ISSUE THREAD

**Issue by schurig** [gutschilla/elixir-pdf-generator#3]
Hey, do you have plans on offering a way to generate pdfs on the fly?
I want to use it for my phoenix framework app without saving the pdf file. I want the generated pdf to be in a variable and display it in the browser.

**Comment by gutschilla** [comment]
Hey, actually yes but calling calling wkhtml without temporary fil has been somewhat unstable. So for now, you have to issue one extra command: 
`pdf = File.read! filename`
Whereas filename is the return value from `{:ok, filename} = PdfGenerator.generate "<html>..."`
Then you may safely set you response's body to `pdf` and set the appropriate headers (Content-Type) and you're done.

But if you reall really need it I wil be happy to add PdfGenerator.generate_binary( html) that does just that: returning the PDF binary.

**Comment by bulleric** [comment]
+1

**Comment by gutschilla** [comment]
Ok ok, going to include tis one-liner ;-) Any ideas how to name this helper? generate_content would be my idea.

**Comment by lATAl** [comment]
+1

**Comment by gutschilla** [comment]
@bulleric @lATAl @schurig So.. this has only taken half a year, but with 0.3.4 (released on hex.pm yesterday) there's a new option `delete_temporary: true` available which can be passed to `PdfGenerator.generate`. I hope this solves your issues.

**Comment by gutschilla** [comment]
Whoops! Wrong issue ;-) PLS stand by.

**Comment by gutschilla** [comment]
@bulleric @lATAl @schurig It's implemented as `PdfGenerator.generate_binary` and `PdfGenerator.generate_binary!` available in 0.3.5. Hiope you like it.
