### ISSUE TITLE
Generate pdf with given url

### ISSUE THREAD

**Issue by vovkats** [gutschilla/elixir-pdf-generator#35]
wkhtmltopdf tool can generate PDF by given URL. E.g.
`wkhtmltopdf http://example.cpm google.pdf`

@gutschilla How can I do it with this library?

**Comment by gutschilla** [comment]
This is not directly supported and not in the scope of that library. But it would be super simple to download the contents of a webpage, let's say google.com with a HTTP library like `HTTPoison` and then feed the downloaded HTML into the generator.

Hope this helps!
