### ISSUE TITLE
Phoenix 1.3 routes?

### ISSUE THREAD

**Issue by niccolox** [gutschilla/elixir-pdf-generator#38]
hi there

is it possible to use this with Phoenix and specify routes that combine to generate a PDF? 

thankyou

**Comment by niccolox** [comment]
maybe something like this, will post my investigations here
http://neuvians.io/2016/02/18/wkhtmltopdf-elixir-plug-for-phoenix/

**Comment by gutschilla** [comment]
@niccolox Yes, elixir-pdf-generator is intended as a library the generate PDFs. You can definitively integrate this with you web service of choice. If you like to see an example, take a look here:

https://github.com/gutschilla/elixir-pdf-server
