### ISSUE TITLE
No 0.3.7 version available on Hex

### ISSUE THREAD

**Issue by pdgonzalez872** [gutschilla/elixir-pdf-generator#40]
Hi!

Hex doesn't seem to have your latest version as stated on the readme. They seem to have `0.3.6` only.
I'm not sure if you were aware of this or not.

https://hex.pm/packages/pdf_generator

**Comment by gutschilla** [comment]
Well, this is a plain "Ooops".

**Comment by gutschilla** [comment]
Fixed in [](https://hex.pm/packages/pdf_generator/0.3.7) Thanks a lot @pdgonzalez872 !
