### ISSUE TITLE
Remove misc_random dependency

### ISSUE THREAD

**Issue by hugomaiavieira** [gutschilla/elixir-pdf-generator#42]
What do you think about embedding the used stuff from `misc_random`? It just a tiny thing to be an extra dependency and also will avoid the [problem on distillery and exrm](https://github.com/gutschilla/elixir-pdf-generator#running-from-within-distillery-or-exrm-releases).

**Comment by gutschilla** [comment]
Yeah, I could do that. Back then (I think this is almost three years) I struggled with many different targets where I had to check for which Erlang version would support which style random.

**Comment by gutschilla** [comment]
Feel free and invited to come up with a small PR on this.

**Comment by gutschilla** [comment]
@hugomaiavieira Released as v0.4.0 – Thanks very much!
