### ISSUE TITLE
Newest version breaks order of options given to wkhtmltopdf

### ISSUE THREAD

**Issue by manukall** [gutschilla/elixir-pdf-generator#47]
Hi @gutschilla,

first of all, thanks for this library which has been generating many PDFs for us so far. :-)

There's a breaking change in the newest version, which I'm not sure was intended: Instead of forwarding `shell_params` as first argument to wkhtmltopdf, they are now put last. This breaks "global options" like `--margin-right`, which have to be put right after `wkhtmltopdf`:

```
Name
       wkhtmltopdf - html to pdf converter

Synopsis
         wkhtmltopdf [GLOBAL OPTION]... [OBJECT]... <output file>
```

**Comment by gutschilla** [comment]
@manukall You are right, I didn't have a test in place for this. I will fix this as soon as possible -  it's Easter holidays here, though. It should be very simple

**Comment by gutschilla** [comment]
@manukall I fixed this in in [v0.5.2](https://hex.pm/packages/pdf_generator/0.5.2) – please let me know if this works for you, now. Thanks for reporting!

**Comment by manukall** [comment]
@gutschilla Thanks! It's working again.

**Comment by gutschilla** [comment]
Thanks for reporting @manukall
