### ISSUE TITLE
v0.5.3 throws when executable path is nil

### ISSUE THREAD

**Issue by radditude** [gutschilla/elixir-pdf-generator#49]
### Background

This project is using `wkhtmltopdf`, so we don't have headless Chrome installed locally or in CI.

### The Issue

Starting the application returns the following error:

```
** (Mix) Could not start application pdf_generator: PdfGenerator.start(:normal, []) returned an error: shutdown: failed to start child: PdfGenerator.PathAgent
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1
            (elixir) lib/io.ex:461: IO.chardata_to_string(nil)
            (elixir) lib/file.ex:214: File.exists?/2
            (pdf_generator) lib/pdf_generator_path_agent.ex:63: PdfGenerator.PathAgent.raise_or_continue/1
            (pdf_generator) lib/pdf_generator_path_agent.ex:37: PdfGenerator.PathAgent.init_opts/1
            (elixir) lib/agent/server.ex:8: Agent.Server.init/1
            (stdlib) gen_server.erl:374: :gen_server.init_it/2
            (stdlib) gen_server.erl:342: :gen_server.init_it/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

It appears that `File.exists?(path)` throws when `path` is nil, so [lines 62 and 63 here](https://github.com/gutschilla/elixir-pdf-generator/blob/HEAD@%7B2019-05-07T16:03:10Z%7D/lib/pdf_generator_path_agent.ex#L62) will always raise if `wkhtml_path` or `chrome_path` is nil.

### Possible fix?

As an experiment, I resolved the error locally by switching line 63 to the following to coerce any `nil`s to an empty string:

```
chrome_exists = File.exists?(options[:chrome_path] || "")
```
That way `File.exists?` will return false for nil paths, and `raise_or_continue` can do its thing and raise or not depending on configuration.

If this seems like a reasonable way to get around the `File.exists?` nil problem, I can open a PR.

Thanks!

**Comment by gutschilla** [comment]
Hey @radditude - thanks a lot for reporting! This is due to me not having a test in place for non-existing Chrome on path. Mea culpa.

Strigifyig via `|| ""` seems fair enough. I'd gladly take a PR for this. Please do the same for the wkhtmltopdf_path as well.

Again, thank you for your collaboration!

**Comment by gutschilla** [comment]
Fixed in https://github.com/gutschilla/elixir-pdf-generator/releases/tag/v0.5.4

**Comment by gutschilla** [comment]
@radditude Thanks a lot for your contribution!
