### ISSUE TITLE
Different Options

### ISSUE THREAD

**Issue by bulleric** [gutschilla/elixir-pdf-generator#5]
Is it possible to pass other wkhtmltopdf options like orientation ?

**Comment by gutschilla** [comment]
Yes, it is. You may pass in any shell parameters that wkhtmltopdf takes.

See (https://hexdocs.pm/pdf_generator/PdfGenerator.html#generate/2) for an example or type

```
h PdfGenerator.generate
```

in your iex shell (issue with `iex -S mix`)

**Comment by afshinhaghighat** [comment]
I could not apply orientation option and it seems it doesn't work. 
```
PDFGenerator.generate(html,
   shell_params: ["--orientation", "Landscape"]
)
```
