### ISSUE TITLE
Issue with System.cmd/3 and arguments

### ISSUE THREAD

**Issue by nacengineer** [gutschilla/elixir-pdf-generator#58]
I'm new to elixir so apologies if this is on my end. 

This is on macOS Sierra with Elixir 1.9.1

```
Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.9.1 (compiled with Erlang/OTP 22
```

[I'm following this example](https://pspdfkit.com/blog/2018/how-to-generate-pdfs-with-elixir/) and it works if I remove the options on the PdfGenerator.generate command. With the options I get the following error 

(My Module is named GlsPdf)

```
iex(4)> GlsPdf.generate_pdf(["Bananas", "Apples", "Yogurt", "Beans", "Potatos"])

11:26:55.019 [debug] {"/usr/local/bin/wkhtmltopdf", ["--dpi", "300", "--page-size", :letter, "/var/folders/z8/247_d97d7y76f3_prnn_q4q80000gp/T/8UQrRJeq.html", "/var/folders/z8/247_d97d7y76f3_prnn_q4q80000gp/T/8UQrRJeq.pdf"]}
** (ArgumentError) all arguments for System.cmd/3 must be binaries
    (elixir) lib/system.ex:782: System.cmd/3
    (pdf_generator) lib/pdf_generator.ex:141: PdfGenerator.generate/2
    (gls_pdf) lib/gls_pdf.ex:26: GlsPdf.generate_pdf/1
```

If I remove the arguments to PdfGenerator.generate it works fine.

**Comment by richthedev** [comment]
I had the same problem, then I changed `page_size: :letter` to `page_size: "letter"` and it worked fine.

**Comment by gutschilla** [comment]
Hi @nacengineer First, sorry for the late reply – you cought that on vacations. Thanks for reporting!

This looks very much as if `pdf_generator` sends an atom (`:letter`) to the shell which doesn't work. I will have to give the documentation a better look. I am currently switching from `System.cmd` to a NodeJs binding so please allow for another few weeks :grimacing: 

Other than that, did @richthedev 's (Thanks a million for that) insight help you?

**Comment by nacengineer** [comment]
> Hi @nacengineer First, sorry for the late reply – you cought that on vacations. Thanks for reporting!
> 
> This looks very much as if `pdf_generator` sends an atom (`:letter`) to the shell which doesn't work. I will have to give the documentation a better look. I am currently switching from `System.cmd` to a NodeJs binding so please allow for another few weeks 😬
> 
> Other than that, did @richthedev 's (Thanks a million for that) insight help you?

It did. Also why inject Node dependency if you don't have to? is there a thinking there. Personally I hate anytime I have to rely on JS

**Comment by gutschilla** [comment]
@nacengineer JS is only required for Chromium. wkhtmltopdf will leep relying on the binary.

**Comment by gutschilla** [comment]
Addressed in https://github.com/gutschilla/elixir-pdf-generator/releases/tag/v0.6.0
