### ISSUE TITLE
How to configure pdf_generator to use local installation of chrome-headless-render-pdf and puppeteer?

### ISSUE THREAD

**Issue by ryanzidago** [gutschilla/elixir-pdf-generator#60]
Hello all!

I've already posted this issue in this Elixir Forum post, where I was advised to open an issue on Github: https://elixirforum.com/t/how-to-configure-pdf-generator-to-use-local-installation-of-chrome-headless-render-pdf-and-puppeteer/28714

Maybe I'll some guidance here too. But here is a copy just in case: 

I managed to use pdf_generator with chrome-headless-render-pdf and puppeteer installed globally. Now I'd rather have both packages installed locally, however I couldn't find a way to make it work. 

I tried to install both packages within the `/assets` folder by running the `npm install chrome-headless-render-pdf puppeteer` command. 

This did not work as pdf_generator expect `chrome-headless-render-pdf` to be in `_build/dev/lib/pdf_generator/priv/node_modules/chrome-headless-render-pdf/dist/cli/chrome-headless-render-pdf.js`

After reading the [README.md](https://github.com/gutschilla/elixir-pdf-generator), and implementing the instructions for a local chrome install, I still get the same error. 

Basically what I did is:
-  added `{:pdf_generator, ">=0.6.0", compile: "make chrome"}` to `mix.exs`
- run `make priv/node_modules` which returns me this error `make: *** No rule to make target 'priv/node_modules'.  Stop.`
- run `cd priv && npm install` and rerun the above mentioned command, which still gets me the same make error.
- run `mix deps.get` and `mix phx.server` which return me this error `make: *** No rule to make target 'chrome'.  Stop.
 ** (Mix) Could not compile dependency :pdf_generator, "make chrome" command failed. You can recompile this dependency with "mix deps.compile pdf_generator", update it with "mix deps.update pdf_generator" or clean it with "mix deps.clean pdf_generator"` with none of the mentioned command working.

Any tipps?

I have `GNU Make 4.1`, `nodejs v12.14.1`, `npm 6.13.4` and `Elixir 1.10.0`.

**Comment by gutschilla** [comment]
Hi @ryanzidago ,

thanks for reporting the issue. I'll look into that. Unfortunately I won't be able to dive deeply into this until next week. Until then all I can advise you is to use the globally-installed binaries.

I'll keep you posted.

**Comment by ryanzidago** [comment]
Alright @gutschilla , thanks for looking into it!

**Comment by manuel-rubio** [comment]
Installing via Hex the priv directory is missing, in the same way like different files... I solved this using:

```
{:pdf_generator, "~> 0.6.0", github: "gutschilla/elixir-pdf-generator", compile: "make chrome"},
```

**Comment by gutschilla** [comment]
@manuel-rubio thanks for pointing this out! :+1:

**Comment by gutschilla** [comment]
Adressed in https://github.com/gutschilla/elixir-pdf-generator/releases/tag/v0.6.2

Using hex shpould be fine now. The mix file was missing the priv dir. Again, thanks a lot for reporting the issue!
