### ISSUE TITLE
Blank PDF being generated

### ISSUE THREAD

**Issue by pedrocaseiro** [gutschilla/elixir-pdf-generator#75]
First, thanks for this package, super helpful.

I'm having an issue where I'm trying to generate a PDF from HTML. I'm using bbmustache to generate the HTML from a template and a set of tokens. My result is:
```
"<html>\n  <body>\n    <div>\n      <p><strong>Booking ID: the booking id</strong></p>\n    </div>\n  </body>\n</html>\n"
```

When I pipe the result above into `|> PdfGenerator.generate_binary!() |> (&File.write("#{pdf_path}.pdf", &1)).()`, it generates a PDF with the correct name and path, but it's completely blank. Any idea what could be causing this?

Thanks!

**Comment by pedrocaseiro** [comment]
I'm using Docker to run my app. By adding the xvfb dependency it now generates the PDF, but with no style since I don't yet have chromium installed.
I've changed my mix.exs to have `{:pdf_generator, "~> 0.6.2", github: "gutschilla/elixir-pdf-generator", compile: "make chrome"},` but now I get the following error:
```
document_service_web | Unchecked dependencies for environment dev:
document_service_web | * pdf_generator (https://github.com/gutschilla/elixir-pdf-generator.git)
document_service_web |   could not find an app file at "_build/dev/lib/pdf_generator/ebin/pdf_generator.app". This may happen if the dependency was not yet compiled or the dependency indeed has no app file (then you can pass app: false as option)
document_service_web | ** (Mix) Can't continue due to errors on dependencies
document_service_web | make: Nothing to be done for 'chrome'
```

**Comment by benonymus** [comment]
@pedrocaseiro How did you solve this? 
I am getting the same result.
